select * from aluno;

DECLARE
    vra   NUMBER := &ra;
    vnome VARCHAR2(30) := '&nome';
BEGIN
    INSERT INTO aluno VALUES (
        vra,
        vnome
    );
COMMIT;
END;


-------------------------- PROCEDURE INSERT
CREATE OR REPLACE PROCEDURE PRD_INSERT_ALUNO (
    P_RA ALUNO.RA%TYPE,
    P_NOME ALUNO.NOME%TYPE
) IS
BEGIN
    INSERT INTO aluno VALUES (
        P_RA,
        P_NOME
    );
COMMIT;
END;


-------------------------------- PROCEDURE UPDATE
CREATE OR REPLACE PROCEDURE PRD_UPDATE_ALUNO (
    P_RA ALUNO.RA%TYPE,
    P_NOME ALUNO.NOME%TYPE
) IS
BEGIN
    UPDATE ALUNO
    SET NOME = P_NOME
    WHERE
    RA = P_RA;
COMMIT;
END;


-------------------------------- PROCEDURE DELETE
CREATE OR REPLACE PROCEDURE PRD_DELETE_ALUNO (
    P_RA ALUNO.RA%TYPE,
    P_NOME ALUNO.NOME%TYPE
) IS
BEGIN
    DELETE 
    FROM ALUNO 
    WHERE RA = P_RA;
COMMIT;
END;


-------------------------------- PROCEDURE 
-- FAZER UM DELETE NA TABELA_VENDAS COM UM COMMIT, A CADA 200 REGISTROS.
CREATE OR REPLACE PROCEDURE prd_delete_vendas IS
    contador NUMBER := 0;
BEGIN
    FOR x IN (
        SELECT
            *
        FROM
            tabela_vendas
    ) LOOP
        DELETE FROM tabela_vendas
        WHERE
            ordernumber = x.ORDERNUMBER;

        IF MOD(contador, 200) = 0 THEN
            COMMIT;
        END IF;
        CONTADOR := CONTADOR + 1;
    END LOOP;
END;

-------------------------------- PROCEDURE 
CREATE OR REPLACE PROCEDURE PRD_INSERT_PEDIDO (
    CODIGO_PEDIDO PEDIDO.COD_PEDIDO%TYPE,
    CODIGO_P_RELACIONADO PEDIDO.COD_PEDIDO_RELACIONADO%TYPE,
    CODIGO_CLIENTE PEDIDO.COD_CLIENTE%TYPE,
    CODIGO_USUARIO PEDIDO.COD_USUARIO%TYPE,
    CODIGO_VENDEDOR PEDIDO.COD_VENDEDOR%TYPE,
    DATA_PEDIDO PEDIDO.DAT_PEDIDO%TYPE,
    DATA_CANC PEDIDO.DAT_CANCELAMENTO%TYPE,
    DATA_ENTR PEDIDO.DAT_ENTREGA%TYPE,
    TOTAL PEDIDO.VAL_TOTAL_PEDIDO%TYPE,
    DESCONTO PEDIDO.VAL_DESCONTO%TYPE,
    ENDERECO PEDIDO.SEQ_ENDERECO_CLIENTE%TYPE,
    P_STATUS PEDIDO.STATUS%TYPE
) IS
BEGIN
    INSERT INTO PEDIDO VALUES (
        CODIGO_PEDIDO,
        CODIGO_P_RELACIONADO,
        CODIGO_CLIENTE,
        CODIGO_USUARIO,
        CODIGO_VENDEDOR,
        DATA_PEDIDO,
        DATA_CANC,
        DATA_ENTR,
        TOTAL,
        DESCONTO,
        ENDERECO,
        P_STATUS
        
    );
COMMIT;
END;